spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:me.leel.notificationservice.dto.OrderPlacedEvent
      group-id: notificationId

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pass@localhost:8761/eureka
server:
  port: 0
