spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/product

      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order

      routes[2]:
        id: inventory-service
        uri: lb://inventory-service
        predicates[0]: Path=/api/inventory
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
