eureka:
  instance:
    hostname: localhost
  client:geagaegaegegg
    register-with-eureka: false
    fetch-registry: false
  username: ${USERNAME:user}
  password: ${PASSWORD:pass}

server:
  port: 8761
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.00124

  ## this is to get orders