spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service?createDatabaseIfNotExist=true

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pass@localhost:8761/eureka