spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service?createDatabaseIfNotExist=true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka