spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service?createDatabaseIfNotExist=true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pass@localhost:8761/eureka